server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Tipos MIME básicos (por si acaso)
  include /etc/nginx/mime.types;

  # Cache estáticos
  location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|woff2|woff|ttf|eot|json|kmz|kml)$ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }

  # HTML sin cache fuerte (para que actualice rápido)
  location ~* \.(?:html)$ {
    try_files $uri =404;
    add_header Cache-Control "no-store";
  }

  # Default: servir archivo si existe
  location / {
    try_files $uri $uri/ =404;
  }
}
